[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["*.js", "*.css"]

[project]
name = "mkdocs-mark-as-read"
version = "0.0.1"
dependencies = ["mkdocs"]
requires-python = ">=3.9"

[project.entry-points."mkdocs.plugins"]
mark-as-read = "mkdocs_mark_as_read.plugin:MarkAsReadPlugin"

[tool.ruff]
line-length = 100
