name: Deploy Docs to GitHub Pages

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: requirements/docs.txt

      - name: Install dependencies
        run: pip install -r requirements/docs.txt

      - name: Build website
        run: |
          mkdocs build --clean
          mkdocs --version

      - name: Adjust permissions
        run: |
          chmod -c -R +rX site/ | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
